include: package:lints/recommended.yaml

analyzer:
  errors:
    todo: warning
    avoid_print: ignore
    avoid_function_literals_in_foreach_calls: ignore
    invalid_annotation_target: ignore

  exclude:
    - "**/*.gr.dart"
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gen.dart"
    - "**/__brick__/**"
    - "build/**"
linter:
  rules:
    - prefer_single_quotes
    - unawaited_futures
